In [3]:
import pandas as pd
import numpy as np
import pathlib as Path

In [4]:
from pathlib import Path

DATA_PATH = Path("./data")

list(DATA_PATH.iterdir())

[WindowsPath('data/T_ONTIME_REPORTING.csv')]

In [5]:
df = pd.read_csv(DATA_PATH / "T_ONTIME_REPORTING.csv")

In [6]:
df.shape

(539747, 20)

In [7]:
df.head()

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME_BLK,CRS_ARR_TIME,ARR_DELAY,ARR_DEL15,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,DISTANCE
0,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1,"New York, NY",NY,"Los Angeles, CA",CA,659,0600-0659,1020,-7.0,0.0,0.0,0.0,381.0,2475.0
1,2025,1,1,3,1/1/2025 12:00:00 AM,AA,10,"Los Angeles, CA",CA,"New York, NY",NY,2200,2200-2259,630,-47.0,0.0,0.0,0.0,330.0,2475.0
2,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1002,"Madison, WI",WI,"Charlotte, NC",NC,644,0600-0659,1005,20.0,1.0,0.0,0.0,141.0,708.0
3,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1004,"Philadelphia, PA",PA,"Las Vegas, NV",NV,1855,1800-1859,2134,-7.0,0.0,0.0,0.0,339.0,2176.0
4,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1005,"Chicago, IL",IL,"Phoenix, AZ",AZ,830,0800-0859,1131,44.0,1.0,0.0,0.0,241.0,1440.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539747 entries, 0 to 539746
Data columns (total 20 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   YEAR               539747 non-null  int64
 1   MONTH              539747 non-null  int64
 2   DAY_OF_MONTH       539747 non-null  int64
 3   DAY_OF_WEEK        539747 non-null  int64
 4   FL_DATE            539747 non-null  object
 5   OP_UNIQUE_CARRIER  539747 non-null  object
 6   OP_CARRIER_FL_NUM  539747 non-null  int64
 7   ORIGIN_CITY_NAME   539747 non-null  object
 8   ORIGIN_STATE_ABR   539747 non-null  object
 9   DEST_CITY_NAME     539747 non-null  object
 10  DEST_STATE_ABR     539747 non-null  object
 11  CRS_DEP_TIME       539747 non-null  int64
 12  DEP_TIME_BLK       539747 non-null  object
 13  CRS_ARR_TIME       539747 non-null  int64
 14  ARR_DELAY          522269 non-null  float64
 15  ARR_DEL15          522269 non-null  float64
 16  CANCELLED          539747 non-null  float64
 17  DIVERTED           539747 non-null  float64
 18  CRS_ELAPSED_TIME   539747 non-null  float64
 19  DISTANCE           539747 non-null  float64
dtypes: float64(6), int64(7), object(7)
memory usage: 82.4+ MB

In [9]:
df.isnull().sum().sort_values(ascending=False)

ARR_DEL15            17478
ARR_DELAY            17478
YEAR                     0
MONTH                    0
DAY_OF_WEEK              0
DAY_OF_MONTH             0
FL_DATE                  0
OP_UNIQUE_CARRIER        0
ORIGIN_STATE_ABR         0
DEST_CITY_NAME           0
OP_CARRIER_FL_NUM        0
ORIGIN_CITY_NAME         0
CRS_DEP_TIME             0
DEST_STATE_ABR           0
CRS_ARR_TIME             0
DEP_TIME_BLK             0
CANCELLED                0
DIVERTED                 0
CRS_ELAPSED_TIME         0
DISTANCE                 0
dtype: int64

In [10]:
df[df["ARR_DEL15"].isnull()][["CANCELLED", "DIVERTED"]].value_counts()

CANCELLED  DIVERTED
1.0        0.0         16312
0.0        1.0          1166
Name: count, dtype: int64

In [11]:
df_clean = df[
    (df["CANCELLED"] == 0) &
    (df["DIVERTED"] == 0)
].copy()

df_clean.shape

(522269, 20)

In [12]:
df_clean["ARR_DEL15"].value_counts()

ARR_DEL15
0.0    424139
1.0     98130
Name: count, dtype: int64

In [13]:
df_clean["ARR_DEL15"].value_counts(normalize=True) * 100

ARR_DEL15
0.0    81.210832
1.0    18.789168
Name: proportion, dtype: float64

In [14]:
df_clean.duplicated().sum()

np.int64(0)

In [15]:
df_clean.nunique().sort_values()

YEAR                    1
MONTH                   1
DIVERTED                1
CANCELLED               1
ARR_DEL15               2
DAY_OF_WEEK             7
OP_UNIQUE_CARRIER      14
DEP_TIME_BLK           19
DAY_OF_MONTH           31
FL_DATE                31
ORIGIN_STATE_ABR       52
DEST_STATE_ABR         52
DEST_CITY_NAME        323
ORIGIN_CITY_NAME      323
CRS_ELAPSED_TIME      466
ARR_DELAY            1153
CRS_DEP_TIME         1209
CRS_ARR_TIME         1310
DISTANCE             1487
OP_CARRIER_FL_NUM    6388
dtype: int64

In [16]:
df_clean.describe()

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,OP_CARRIER_FL_NUM,CRS_DEP_TIME,CRS_ARR_TIME,ARR_DELAY,ARR_DEL15,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,DISTANCE
count,522269.0,522269.0,522269.000000,522269.000000,522269.000000,522269.000000,522269.000000,522269.000000,522269.000000,522269.0,522269.0,522269.000000,522269.000000
mean,2025.0,1.0,15.901246,4.021271,2482.055918,1315.261628,1502.718465,3.756614,0.187892,0.0,0.0,151.882727,847.164503
std,0.0,0.0,9.060014,1.926226,1665.910307,479.664906,501.501217,56.850884,0.390626,0.0,0.0,74.141967,601.919212
min,2025.0,1.0,1.000000,1.000000,1.000000,5.000000,1.000000,-87.000000,0.000000,0.0,0.0,25.000000,31.000000
25%,2025.0,1.0,8.000000,2.000000,1106.000000,905.000000,1118.000000,-18.000000,0.000000,0.0,0.0,96.000000,403.000000
50%,2025.0,1.0,16.000000,4.000000,2202.000000,1310.000000,1524.000000,-8.000000,0.000000,0.0,0.0,136.000000,712.000000
75%,2025.0,1.0,24.000000,6.000000,3686.000000,1724.000000,1922.000000,7.000000,0.000000,0.0,0.0,184.000000,1085.000000
max,2025.0,1.0,31.000000,7.000000,8819.000000,2359.000000,2359.000000,3282.000000,1.000000,0.0,0.0,693.000000,5095.000000

In [17]:
df_clean[
    [
        "CRS_DEP_TIME",
        "CRS_ARR_TIME",
        "CRS_ELAPSED_TIME",
        "DISTANCE",
        "ARR_DELAY"
    ]
].describe()

,CRS_DEP_TIME,CRS_ARR_TIME,CRS_ELAPSED_TIME,DISTANCE,ARR_DELAY
count,522269.000000,522269.000000,522269.000000,522269.000000,522269.000000
mean,1315.261628,1502.718465,151.882727,847.164503,3.756614
std,479.664906,501.501217,74.141967,601.919212,56.850884
min,5.000000,1.000000,25.000000,31.000000,-87.000000
25%,905.000000,1118.000000,96.000000,403.000000,-18.000000
50%,1310.000000,1524.000000,136.000000,712.000000,-8.000000
75%,1724.000000,1922.000000,184.000000,1085.000000,7.000000
max,2359.000000,2359.000000,693.000000,5095.000000,3282.000000

In [18]:
df_clean.columns.tolist()

['YEAR',
 'MONTH',
 'DAY_OF_MONTH',
 'DAY_OF_WEEK',
 'FL_DATE',
 'OP_UNIQUE_CARRIER',
 'OP_CARRIER_FL_NUM',
 'ORIGIN_CITY_NAME',
 'ORIGIN_STATE_ABR',
 'DEST_CITY_NAME',
 'DEST_STATE_ABR',
 'CRS_DEP_TIME',
 'DEP_TIME_BLK',
 'CRS_ARR_TIME',
 'ARR_DELAY',
 'ARR_DEL15',
 'CANCELLED',
 'DIVERTED',
 'CRS_ELAPSED_TIME',
 'DISTANCE']

In [19]:
df_clean.head()

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME_BLK,CRS_ARR_TIME,ARR_DELAY,ARR_DEL15,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,DISTANCE
0,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1,"New York, NY",NY,"Los Angeles, CA",CA,659,0600-0659,1020,-7.0,0.0,0.0,0.0,381.0,2475.0
1,2025,1,1,3,1/1/2025 12:00:00 AM,AA,10,"Los Angeles, CA",CA,"New York, NY",NY,2200,2200-2259,630,-47.0,0.0,0.0,0.0,330.0,2475.0
2,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1002,"Madison, WI",WI,"Charlotte, NC",NC,644,0600-0659,1005,20.0,1.0,0.0,0.0,141.0,708.0
3,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1004,"Philadelphia, PA",PA,"Las Vegas, NV",NV,1855,1800-1859,2134,-7.0,0.0,0.0,0.0,339.0,2176.0
4,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1005,"Chicago, IL",IL,"Phoenix, AZ",AZ,830,0800-0859,1131,44.0,1.0,0.0,0.0,241.0,1440.0

In [20]:
target = "ARR_DEL15"

In [21]:
drop_columns = [
    "ARR_DEL15",
    "ARR_DELAY",
    "CANCELLED",
    "DIVERTED",
    "YEAR",
    "MONTH"
]

In [22]:
X = df_clean.drop(columns=drop_columns)

In [23]:
y = df_clean[target]

In [25]:
X.shape , y.shape

((522269, 14), (522269,))

In [26]:
df_clean["FL_DATE"].min(), df_clean["FL_DATE"].max()

('1/1/2025 12:00:00 AM', '1/9/2025 12:00:00 AM')

In [27]:
df_clean["FL_DATE"].value_counts().sort_index()

FL_DATE
1/1/2025 12:00:00 AM     16771
1/10/2025 12:00:00 AM    14983
1/11/2025 12:00:00 AM    14264
1/12/2025 12:00:00 AM    18261
1/13/2025 12:00:00 AM    17762
1/14/2025 12:00:00 AM    15738
1/15/2025 12:00:00 AM    16027
1/16/2025 12:00:00 AM    18469
1/17/2025 12:00:00 AM    18380
1/18/2025 12:00:00 AM    14661
1/19/2025 12:00:00 AM    15993
1/2/2025 12:00:00 AM     19431
1/20/2025 12:00:00 AM    18135
1/21/2025 12:00:00 AM    14384
1/22/2025 12:00:00 AM    14876
1/23/2025 12:00:00 AM    17713
1/24/2025 12:00:00 AM    18029
1/25/2025 12:00:00 AM    14983
1/26/2025 12:00:00 AM    18630
1/27/2025 12:00:00 AM    17971
1/28/2025 12:00:00 AM    15891
1/29/2025 12:00:00 AM    15968
1/3/2025 12:00:00 AM     19228
1/30/2025 12:00:00 AM    17309
1/31/2025 12:00:00 AM    17735
1/4/2025 12:00:00 AM     18257
1/5/2025 12:00:00 AM     18151
1/6/2025 12:00:00 AM     16816
1/7/2025 12:00:00 AM     15445
1/8/2025 12:00:00 AM     16071
1/9/2025 12:00:00 AM     15937
Name: count, dtype: int64

In [28]:
df_clean["FL_DATE"] = pd.to_datetime(df_clean["FL_DATE"])

df_clean["FL_DATE"].min(), df_clean["FL_DATE"].max()

C:\Users\sahil\AppData\Local\Temp\ipykernel_16920\3417552328.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_clean["FL_DATE"] = pd.to_datetime(df_clean["FL_DATE"])

(Timestamp('2025-01-01 00:00:00'), Timestamp('2025-01-31 00:00:00'))

In [29]:
df_clean["FL_DATE"].value_counts().sort_index()

FL_DATE
2025-01-01    16771
2025-01-02    19431
2025-01-03    19228
2025-01-04    18257
2025-01-05    18151
2025-01-06    16816
2025-01-07    15445
2025-01-08    16071
2025-01-09    15937
2025-01-10    14983
2025-01-11    14264
2025-01-12    18261
2025-01-13    17762
2025-01-14    15738
2025-01-15    16027
2025-01-16    18469
2025-01-17    18380
2025-01-18    14661
2025-01-19    15993
2025-01-20    18135
2025-01-21    14384
2025-01-22    14876
2025-01-23    17713
2025-01-24    18029
2025-01-25    14983
2025-01-26    18630
2025-01-27    17971
2025-01-28    15891
2025-01-29    15968
2025-01-30    17309
2025-01-31    17735
Name: count, dtype: int64

In [30]:
df_clean["FL_DATE"].min(), df_clean["FL_DATE"].max()

(Timestamp('2025-01-01 00:00:00'), Timestamp('2025-01-31 00:00:00'))

In [31]:
df_clean.groupby("FL_DATE").size()

FL_DATE
2025-01-01    16771
2025-01-02    19431
2025-01-03    19228
2025-01-04    18257
2025-01-05    18151
2025-01-06    16816
2025-01-07    15445
2025-01-08    16071
2025-01-09    15937
2025-01-10    14983
2025-01-11    14264
2025-01-12    18261
2025-01-13    17762
2025-01-14    15738
2025-01-15    16027
2025-01-16    18469
2025-01-17    18380
2025-01-18    14661
2025-01-19    15993
2025-01-20    18135
2025-01-21    14384
2025-01-22    14876
2025-01-23    17713
2025-01-24    18029
2025-01-25    14983
2025-01-26    18630
2025-01-27    17971
2025-01-28    15891
2025-01-29    15968
2025-01-30    17309
2025-01-31    17735
dtype: int64

In [32]:
train_df = df_clean[df_clean["FL_DATE"] <= "2025-01-21"].copy()

val_df = df_clean[
    (df_clean["FL_DATE"] >= "2025-01-22") &
    (df_clean["FL_DATE"] <= "2025-01-26")
].copy()

test_df = df_clean[df_clean["FL_DATE"] >= "2025-01-27"].copy()

train_df.shape, val_df.shape, test_df.shape

((353164, 20), (84231, 20), (84874, 20))

In [33]:
print("TRAIN")
print(train_df["ARR_DEL15"].value_counts(normalize=True) * 100)

print("\nVALIDATION")
print(val_df["ARR_DEL15"].value_counts(normalize=True) * 100)

print("\nTEST")
print(test_df["ARR_DEL15"].value_counts(normalize=True) * 100)

TRAIN
ARR_DEL15
0.0    78.672232
1.0    21.327768
Name: proportion, dtype: float64

VALIDATION
ARR_DEL15
0.0    84.084245
1.0    15.915755
Name: proportion, dtype: float64

TEST
ARR_DEL15
0.0    88.922403
1.0    11.077597
Name: proportion, dtype: float64

In [34]:
def add_date_features(data):
    data = data.copy()

    data["DAY_OF_MONTH"] = data["FL_DATE"].dt.day
    data["DAY_OF_WEEK"] = data["FL_DATE"].dt.dayofweek
    data["WEEK_OF_MONTH"] = ((data["FL_DATE"].dt.day - 1) // 7) + 1

    return data

In [35]:
train_df = add_date_features(train_df)
val_df = add_date_features(val_df)
test_df = add_date_features(test_df)

In [36]:
train_df.shape

(353164, 21)

In [37]:
train_df.head(
    
)

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST_CITY_NAME,...,CRS_DEP_TIME,DEP_TIME_BLK,CRS_ARR_TIME,ARR_DELAY,ARR_DEL15,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,DISTANCE,WEEK_OF_MONTH
0,2025,1,1,2,2025-01-01,AA,1,"New York, NY",NY,"Los Angeles, CA",...,659,0600-0659,1020,-7.0,0.0,0.0,0.0,381.0,2475.0,1
1,2025,1,1,2,2025-01-01,AA,10,"Los Angeles, CA",CA,"New York, NY",...,2200,2200-2259,630,-47.0,0.0,0.0,0.0,330.0,2475.0,1
2,2025,1,1,2,2025-01-01,AA,1002,"Madison, WI",WI,"Charlotte, NC",...,644,0600-0659,1005,20.0,1.0,0.0,0.0,141.0,708.0,1
3,2025,1,1,2,2025-01-01,AA,1004,"Philadelphia, PA",PA,"Las Vegas, NV",...,1855,1800-1859,2134,-7.0,0.0,0.0,0.0,339.0,2176.0,1
4,2025,1,1,2,2025-01-01,AA,1005,"Chicago, IL",IL,"Phoenix, AZ",...,830,0800-0859,1131,44.0,1.0,0.0,0.0,241.0,1440.0,1

In [38]:
def add_time_features(data):
    data = data.copy()

    # Convert HHMM format into hour and minute
    data["DEP_HOUR"] = data["CRS_DEP_TIME"] // 100
    data["DEP_MINUTE"] = data["CRS_DEP_TIME"] % 100

    # Same for scheduled arrival
    data["ARR_HOUR"] = data["CRS_ARR_TIME"] // 100
    data["ARR_MINUTE"] = data["CRS_ARR_TIME"] % 100

    return data

In [39]:
train_df = add_time_features(train_df)
val_df = add_time_features(val_df)
test_df = add_time_features(test_df)

In [40]:
train_df[
    ["CRS_DEP_TIME", "DEP_HOUR", "DEP_MINUTE",
     "CRS_ARR_TIME", "ARR_HOUR", "ARR_MINUTE"]
].head()

   CRS_DEP_TIME  DEP_HOUR  DEP_MINUTE  CRS_ARR_TIME  ARR_HOUR  ARR_MINUTE
0           659         6          59          1020        10          20
1          2200        22           0           630         6          30
2           644         6          44          1005        10           5
3          1855        18          55          2134        21          34
4           830         8          30          1131        11          31

In [41]:
def add_time_features(data):
    data = data.copy()

    data["DEP_HOUR"] = data["CRS_DEP_TIME"] // 100
    data["DEP_MINUTE"] = data["CRS_DEP_TIME"] % 100

    data["ARR_HOUR"] = data["CRS_ARR_TIME"] // 100
    data["ARR_MINUTE"] = data["CRS_ARR_TIME"] % 100

    return data

In [42]:
def add_time_features(data):
    data = data.copy()

    data["DEP_HOUR"] = data["CRS_DEP_TIME"] // 100
    data["DEP_MINUTE"] = data["CRS_DEP_TIME"] % 100

    data["ARR_HOUR"] = data["CRS_ARR_TIME"] // 100
    data["ARR_MINUTE"] = data["CRS_ARR_TIME"] % 100

    return data

In [43]:
train_df[
    ["CRS_DEP_TIME", "DEP_HOUR", "DEP_MINUTE",
     "CRS_ARR_TIME", "ARR_HOUR", "ARR_MINUTE"]
].head()

   CRS_DEP_TIME  DEP_HOUR  DEP_MINUTE  CRS_ARR_TIME  ARR_HOUR  ARR_MINUTE
0           659         6          59          1020        10          20
1          2200        22           0           630         6          30
2           644         6          44          1005        10           5
3          1855        18          55          2134        21          34
4           830         8          30          1131        11          31

In [44]:
feature_columns = [
    "DAY_OF_MONTH",
    "DAY_OF_WEEK",
    "WEEK_OF_MONTH",
    "OP_UNIQUE_CARRIER",
    "ORIGIN_CITY_NAME",
    "ORIGIN_STATE_ABR",
    "DEST_CITY_NAME",
    "DEST_STATE_ABR",
    "DEP_HOUR",
    "DEP_MINUTE",
    "ARR_HOUR",
    "ARR_MINUTE",
    "CRS_ELAPSED_TIME",
    "DISTANCE"
]

target = "ARR_DEL15"

X_train = train_df[feature_columns]
y_train = train_df[target]

X_val = val_df[feature_columns]
y_val = val_df[target]

X_test = test_df[feature_columns]
y_test = test_df[target]

X_train.shape, X_val.shape, X_test.shape

((353164, 14), (84231, 14), (84874, 14))

In [49]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import  StandardScaler

In [46]:
numeric_features = [
    "DAY_OF_MONTH",
    "DAY_OF_WEEK",
    "WEEK_OF_MONTH",
    "DEP_HOUR",
    "DEP_MINUTE",
    "ARR_HOUR",
    "ARR_MINUTE",
    "CRS_ELAPSED_TIME",
    "DISTANCE"
]

categorical_features = [
    "OP_UNIQUE_CARRIER",
    "ORIGIN_CITY_NAME",
    "ORIGIN_STATE_ABR",
    "DEST_CITY_NAME",
    "DEST_STATE_ABR"
]

In [47]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            "passthrough",
            numeric_features
        ),
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_features
        )
    ]
)

In [50]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numeric_features
        ),
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ]
)

Creating the dummy classifier , afterwards will compare with logistic regression

In [51]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [52]:
dummy_model = DummyClassifier(strategy="most_frequent")

dummy_model.fit(X_train, y_train)

DummyClassifier(strategy='most_frequent')

In [53]:
dummy_predictions = dummy_model.predict(X_val)

In [54]:
print("Accuracy:", accuracy_score(y_val, dummy_predictions))
print("Precision:", precision_score(y_val, dummy_predictions, zero_division=0))
print("Recall:", recall_score(y_val, dummy_predictions, zero_division=0))
print("F1 Score:", f1_score(y_val, dummy_predictions, zero_division=0))

Accuracy: 0.8408424451805155
Precision: 0.0
Recall: 0.0
F1 Score: 0.0

In [55]:
from sklearn.linear_model import LogisticRegression